services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus_pass
      POSTGRES_DB: campus_stem
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
