"""create platform_controls table

Revision ID: 2edf0d90944e
Revises: 3cd6f0a0bed1
Create Date: 2026-06-23 08:51:10.695457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2edf0d90944e'
down_revision: Union[str, Sequence[str], None] = '3cd6f0a0bed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='platform_controls_singleton_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        sa.text("INSERT INTO platform_controls (id, registration_enabled) VALUES (1, false)")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_controls')
    # ### end Alembic commands ###
