"""create usuarios table

Revision ID: db99f306841a
Revises: 
Create Date: 2026-06-22 17:13:50.787079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db99f306841a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('estudiante', 'admin', 'juez', 'super_admin', name='rolusuario'), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('colegio', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    sa.Enum(name='rolusuario').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
